### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by hbredin** [asteroid-team/torch-audiomentations#25]
Would be nice for reproducibility reasons to be able to instantiate augmentations from a configuration file.

```python
augment = AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.015, p=0.5)
```

would be equivalent to loading from this configuration file:

```yaml
# config.yaml
AddGaussianNoise:
    min_amplitude: 0.001
    max_amplitude: 0.015
    p: 0.5
```

```python
with open('config.yaml', 'r') as fp:
    augment = torch_audiomentations.from_config(yaml.load(fp))
```

Composition could have the following (simple) syntax:

```yaml
# config.yaml
Compose:
    AddGaussianNoise:
        min_amplitude: 0.001
        max_amplitude: 0.015
        p: 0.5
    TimeStretch:
        min_rate: 0.8
        max_rate: 1.25
        p: 0.5
```

Would you consider a PR adding such a feature?
