### ISSUE TITLE
Bug: shift augmentation sometimes produces silent tensor

### ISSUE THREAD

**Issue by janvainer** [asteroid-team/torch-audiomentations#77]
Hi, I was playing with the augmentations in this repo and I am sometimes getting silent audio results with the Shift augmentation. It happens shorter audio files with duration around one second (16319 samples). 
```
  Shift:
      min_shift: -0.1
      max_shift: 0.1
      shift_unit: "fraction"
      rollover: True
      mode: "per_example"
      p: 1
```
Are you able to reproduce this behavior for some short audio? I cannot provide the audio files, but can run more experiments if you wish.
